// src/components/parameters/ParameterName.svelte
<svelte:options immutable={true} />

<script lang="ts">
  import type { FormParameter } from '../../types';
  import { tooltip } from '../../utilities/tooltip';

  export let formParameter: FormParameter;
</script>

<div class="form-parameter-name">
  <div
    class="name"
    class:error={formParameter.error !== null}
    use:tooltip={{ content: formParameter?.name, placement: 'bottom' }}
  >
    {formParameter?.name}
  </div>
</div>

<style>
  .form-parameter-name {
    align-items: center;
    display: flex;
  }

  .name {
    color: var(--st-gray-80);
    cursor: pointer;
    font-style: normal;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .name.error {
    color: var(--st-red);
  }
</style>

// src/app/components/parameters/parameter-name.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  NgModule,
} from '@angular/core';
import { MaterialModule } from '../../material';
import { FormParameter } from '../../types';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'parameter-name',
  styles: [
    `
      :host {
        align-items: center;
        display: flex;
      }

      div {
        color: rgba(0, 0, 0, 0.6);
        cursor: pointer;
        font-size: 14px;
        font-style: normal;
        font-weight: 500;
        letter-spacing: 0.1px;
        line-height: 24px;
        max-width: 100%;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
      }
    `,
  ],
  template: `
    <div [matTooltip]="parameter?.name" matTooltipPosition="above">
      {{ parameter?.name }}
    </div>
  `,
})
export class ParameterNameComponent {
  @Input() parameter: FormParameter | undefined;
}

@NgModule({
  declarations: [ParameterNameComponent],
  exports: [ParameterNameComponent],
  imports: [CommonModule, MaterialModule],
})
export class ParameterNameModule {}
