// src/components/parameters/ParameterBasePath.svelte
<svelte:options immutable={true} />

<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import Input from '../form/Input.svelte';
  import ParameterBaseError from './ParameterBaseError.svelte';
  import ParameterName from './ParameterName.svelte';

  export let formParameter: FormParameter;
  export let labelColumnWidth: number = 200;
  export let level: number = 0;
  export let levelPadding: number = 20;

  const dispatch = createEventDispatcher();

  $: columns = `calc(${labelColumnWidth}px - ${level * levelPadding}px) auto`;

  function onChange(event: Event) {
    const input = event.target as HTMLInputElement;
    if (input.files.length) {
      const file = input.files.item(0);
      formParameter.file = file;
      formParameter.value = file.name;
      dispatch('change', formParameter);
    }
  }
</script>

<div class="parameter-base-path" style="grid-template-columns: {columns}">
  <ParameterName {formParameter} />
  <div class="file-input">
    <Input>
      <input
        bind:value={formParameter.value}
        class="st-input w-100"
        class:error={formParameter.error !== null}
        disabled
        type="text"
      />
    </Input>
    <input type="file" on:change={onChange} />
  </div>
</div>

<ParameterBaseError {columns} {formParameter} />

<style>
  .file-input {
    display: grid;
    gap: 5px;
  }

  .parameter-base-path {
    align-items: center;
    display: grid;
  }
</style>

// src/app/components/parameters/parameter-base-path.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter as E,
  Input,
  NgModule,
  OnChanges,
  Output,
  SimpleChanges,
} from '@angular/core';
import { MaterialModule } from '../../material';
import { FormParameter, FormParameterChange } from '../../types';
import { ParameterNameModule } from './parameter-name.component';
import { parameterStyles } from './parameter-styles';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'parameter-base-path',
  styles: [
    parameterStyles,
    `
      .field {
        display: grid;
        gap: 15px;
        grid-template-columns: 40% auto;
      }
    `,
  ],
  template: `
    <parameter-name [parameter]="parameter"></parameter-name>
    <div class="field">
      <mat-form-field class="file-path" floatLabel="always">
        <mat-label>Path</mat-label>
        <input matInput disabled type="text" [value]="fileName" />
      </mat-form-field>
      <input type="file" (change)="onParameterChange($event)" />
    </div>
  `,
})
export class ParameterBasePathComponent implements OnChanges {
  @Input() parameter: FormParameter | undefined;

  @Output() parameterChange: E<FormParameterChange> = new E();

  fileName = '';

  ngOnChanges(changes: SimpleChanges): void {
    if (changes.parameter) {
      this.fileName = this.parameter.value;
    }
  }

  onParameterChange(event: Event) {
    const input = event.target as HTMLInputElement;
    if (input.files.length) {
      const file = input.files.item(0);
      this.fileName = file.name;
      this.parameterChange.emit({ newValue: file, parameter: this.parameter });
    }
  }
}

@NgModule({
  declarations: [ParameterBasePathComponent],
  exports: [ParameterBasePathComponent],
  imports: [CommonModule, MaterialModule, ParameterNameModule],
})
export class ParameterBasePathModule {}
