// src/components/parameters/ParameterRecStruct.svelte
<svelte:options immutable={true} />

<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import type { FormParameter } from '../../types';
  import ParameterBase from './ParameterBase.svelte';
  import ParameterName from './ParameterName.svelte';
  import ParameterRec from './ParameterRec.svelte';
  import ParameterRecError from './ParameterRecError.svelte';

  const dispatch = createEventDispatcher();

  export let disabled: boolean = false;
  export let formParameter: FormParameter;
  export let labelColumnWidth: number = 200;
  export let level: number = 0;
  export let levelPadding: number = 20;

  let expanded: boolean = false;

  $: subFormParameters = getSubFormParameters(formParameter);

  function getSubFormParameters(formParameter: FormParameter): FormParameter[] {
    const subFormParameters = [];
    const { schema, value = [] } = formParameter;
    const { items: keys } = schema;
    const structKeys = Object.keys(keys).sort();

    for (const key of structKeys) {
      const subFormParameter: FormParameter = {
        error: null,
        key,
        loading: false,
        name: key,
        schema: schema.items[key],
        validate: false,
        value: value ? value[key] || null : null,
      };
      subFormParameters.push(subFormParameter);
    }

    return subFormParameters;
  }

  function onChange(event: CustomEvent<FormParameter>) {
    const { detail: subFormParameter } = event;
    const value = {
      ...formParameter.value,
      [subFormParameter.key]: subFormParameter.value,
    };
    dispatch('change', { ...formParameter, value });
  }

  function toggleExpanded() {
    expanded = !expanded;
  }
</script>

<div class="parameter-rec-struct" on:click={toggleExpanded}>
  {#if !expanded}
    <i class="bi bi-chevron-right" />
  {:else}
    <i class="bi bi-chevron-down" />
  {/if}
  <ParameterName {formParameter} />
</div>

{#if expanded}
  <ul style="padding-inline-start: {levelPadding}px">
    <ParameterRecError {formParameter} />

    {#each subFormParameters as subFormParameter (subFormParameter.name)}
      <li>
        {#if subFormParameter.schema.type === 'series' || subFormParameter.schema.type === 'struct'}
          <ParameterRec
            {disabled}
            formParameter={subFormParameter}
            {labelColumnWidth}
            level={++level}
            {levelPadding}
            on:change={onChange}
          />
        {:else}
          <ParameterBase
            {disabled}
            formParameter={subFormParameter}
            {labelColumnWidth}
            level={++level}
            {levelPadding}
            on:change={onChange}
          />
        {/if}
      </li>
    {/each}
  </ul>
{/if}

<style>
  ul {
    margin: 0;
  }

  li {
    list-style: none;
    margin-bottom: 1rem;
  }

  .parameter-rec-struct {
    align-items: center;
    display: grid;
    gap: 5px;
    grid-template-columns: 16px auto;
    margin-bottom: 1rem;
  }
</style>

// src/app/components/parameters/parameter-rec-struct.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter as E,
  Input,
  NgModule,
  OnChanges,
  Output,
  SimpleChanges,
} from '@angular/core';
import { MaterialModule } from '../../material';
import { FormParameter, FormParameterChange } from '../../types';
import { ParameterBaseModule } from './parameter-base.component';
import { ParameterNameModule } from './parameter-name.component';
import { ParameterRecModule } from './parameter-rec.component';
import { parameterStyles } from './parameter-styles';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'parameter-rec-struct',
  styles: [
    parameterStyles,
    `
      :host {
        display: block;
        padding-left: 0px;
        width: 100%;
      }

      mat-icon {
        color: rgba(0, 0, 0, 0.6);
      }

      ul {
        margin: 0;
        padding-inline-start: 20px;
      }

      li {
        list-style: none;
      }

      .struct {
        cursor: pointer;
        display: flex;
        padding-right: 40px;
        width: 100%;
      }

      .struct-left {
        align-items: center;
        display: flex;
        flex-grow: 1;
      }
    `,
  ],
  template: `
    <div class="struct">
      <div class="struct-left" (click)="toggleExpanded()">
        <mat-icon *ngIf="expanded">expand_more</mat-icon>
        <mat-icon *ngIf="!expanded">chevron_right</mat-icon>
        <parameter-name [parameter]="parameter"></parameter-name>
      </div>
    </div>

    <ul *ngIf="expanded">
      <li
        *ngFor="
          let subParameter of subParameters;
          trackBy: trackBySubParameters
        "
      >
        <parameter-base
          *ngIf="
            subParameter.schema.type !== 'series' &&
            subParameter.schema.type !== 'struct'
          "
          [parameter]="subParameter"
          (parameterChange)="onParameterChange($event)"
        ></parameter-base>

        <parameter-rec
          *ngIf="
            subParameter.schema.type === 'series' ||
            subParameter.schema.type === 'struct'
          "
          [parameter]="subParameter"
          (parameterChange)="onParameterChange($event)"
        ></parameter-rec>
      </li>
    </ul>
  `,
})
export class ParameterRecStructComponent implements OnChanges {
  @Input() parameter: FormParameter | undefined;

  @Output() parameterChange: E<FormParameterChange> = new E();

  expanded = false;
  subParameters: FormParameter[];

  ngOnChanges(changes: SimpleChanges) {
    if (changes.parameter) {
      this.updateSubParameters();
    }
  }

  onParameterChange(change: FormParameterChange) {
    const newValue = {
      ...this.parameter.value,
      [change.parameter.key]: change.newValue,
    };
    const newChange = {
      newValue,
      parameter: this.parameter,
    };
    this.parameterChange.emit(newChange);
  }

  toggleExpanded() {
    this.expanded = !this.expanded;
  }

  trackBySubParameters(_: number, parameter: FormParameter) {
    return parameter.name;
  }

  updateSubParameters() {
    this.subParameters = [];
    const { items: keys } = this.parameter.schema;
    const { value } = this.parameter;
    const structKeys = Object.keys(keys).sort();
    for (const key of structKeys) {
      const subParameter: FormParameter = {
        error: null,
        key,
        loading: false,
        name: key,
        schema: this.parameter.schema.items[key],
        value: value ? value[key] || null : null,
      };
      this.subParameters.push(subParameter);
    }
  }
}

@NgModule({
  declarations: [ParameterRecStructComponent],
  exports: [ParameterRecStructComponent],
  imports: [
    CommonModule,
    MaterialModule,
    ParameterBaseModule,
    ParameterNameModule,
    ParameterRecModule,
  ],
})
export class ParameterRecStructModule {}
